# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Michael Bender"
description: > # this means to ignore newlines until "email:"
   software, business, and family

email: "michaelbenbender@gmail.com"
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cover1.jpg"

name: 'Michael Bender'
author: 'Michael Bender'
#author_image: "http://gravatar.com/avatar/159491a8e4ac83ad9568072b5a5ae831"
author_image: "/assets/images/faceclose.jpg"

paginate:	5

url: "http://michaelbender.net" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/bender_michael
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/michael-bender
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

  - icon:	camera-retro
    url:	https://instagram.com/michaelbenbender/
    desc:	Check me out on instagram
    share_url:
    share_title:
    share_link:

  - icon:	stack-overflow
    url:	http://stackoverflow.com/users/821870/michael
    desc:	Help me on stackoverflow
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	http://www.linkedin.com/pub/michael-bender/4/515/b70
    desc:	I'm professional on linkedin
    share_url:
    share_title:
    share_link:
